---
# cicdhub is the host on which kubeadm, CICDHub and CICDHub reverse proxy are installed
- hosts: cicdhub
  become: true
  gather_facts: yes
  become_method: sudo
  vars_files:
    - ansible-variables-microk8s.yml
  tasks:
    - import_role:
        name: initial-setup

    - import_role:
        name: microk8s
      when: microk8s|default(True)|bool == True

    - import_role:
        name: helm
      when: helm|default(False)|bool == True

    - import_role:
        name: cicdhub
      when: cicdhub|default(False)|bool == True

    - import_role:
        name: cicdhub-proxy
      when: cicdhub|default(False)|bool == True