- name: Get OS release
  raw: lsb_release -c 
  register: lsb_release

- name: Set OS release variable
  set_fact:
    os_release: "{{ lsb_release.stdout.split(':')[1] | trim }}"

- name: Update apt cache
  raw: apt-get -y update

- name: If needed, install Python
  raw: apt-get -y install python python-pip

- name: Install base dependencies
  apt: 
    name: 
      - python
      - python-pip
      - apt-transport-https
      - ca-certificates
      - curl
      - build-essential
      - git
      - software-properties-common
      - openvswitch-switch
      - htop
    state: present 
  become: yes

- name: Set Hostname
  hostname:
    name: "{{hostname}}"

- name: Install Pip dependencies
  pip:
    name:
      - jsonpointer>=2.0
      - twine>=1.13.0

- name: Gather Facts
  setup: 

- name: Add hostname to hosts file
  lineinfile: 
    dest: /etc/hosts 
    line: "{{ advertise_address|default(hostvars[inventory_hostname]['ansible_default_ipv4']['address']) }} {{hostname}}" 
    state: present

- name: Make sure Apache2 uninstalled (port 80 use conflicts with microk8s ingress controller)
  apt: 
    name: apache2
    state: absent

- name: Get users homedir
  local_action: command echo ~
  register: homedir

- name: Clean /root/.kube directory
  file:
    state: absent
    path: "/root/.kube"
  become: yes

- name: Clean /root/.helm directory
  file:
    state: absent
    path: "/root/.helm"
  become: yes

- name: Clean /etc/kubernetes directory
  file:
    state: absent
    path: "/etc/kubernetes"
  become: yes