- name: Get OS release
  raw: lsb_release -c 
  register: lsb_release

- name: Set OS release variable
  set_fact:
    os_release: "{{ lsb_release.stdout.split(':')[1] | trim }}"

- name: Check for correct OS version
  fail:
    msg: "CICDHub requires Ubuntu Xenial and the OS is {{ os_release }}"
  when: "os_release != 'xenial'"

- name: Update apt cache
  raw: apt-get -y update

- name: If needed, install Python
  raw: apt-get -y install python python-pip

- name: Install base dependencies
  apt: 
    name: 
      - python
      - python-pip
      - apt-transport-https
      - ca-certificates
      - curl
      - build-essential
      - git
      - software-properties-common
      - openvswitch-switch
      - htop
    state: present 
  become: yes

- name: Set Hostname
  hostname:
    name: "{{hostname}}"

- name: Install Pip dependencies
  pip:
    name:
      - jsonpointer>=2.0
      - twine>=1.13.0

- name: Gather Facts
  setup: 

- name: Add hostname to hosts file
  lineinfile: 
    dest: /etc/hosts 
    line: "{{ advertise_address|default(hostvars[inventory_hostname]['ansible_default_ipv4']['address']) }} {{hostname}}" 
    state: present