testing:
  description: Jenkins testing
  alm:
    ip_address: {{cicdhub_addr_ip}}
    port: '8081'
{% if lm_secure|default(False)|bool == True %}
    secure_port: True
    username: jack
    auth_address: {{cicdhub_addr_ip}}
    auth_port: '8080'
    password: jack
{% else %}
    secure_port: False
{% endif %}
  arm:
    defaultrm:
      ip_address: {{cicdhub_addr_ip}}
{% if arm_secure|default(False)|bool == True %}
      port: '31081'
      secure_port: True
      onboarding_addr: https://osslm-ansible-rm:8443
{% else %}
      port: '31080'
      secure_port: False
      onboarding_addr: http://osslm-ansible-rm:8080
{% endif %}
