cicdhub_proxy_ssl: False

cicdhub_main_proxy_port: 8180
cicdhub_main_proxy_ssl_port: 8443

cicdhub_docker_registry_proxy_target_host: docker-registry.cicdhub
cicdhub_docker_registry_proxy_port: 8000
cicdhub_docker_registry_proxy_ssl_port: 8100
cicdhub_docker_registry_non_ssl_port: 32080
cicdhub_docker_registry_ssl_port: 32443

cicdhub_git_proxy_target_host: git.cicdhub
cicdhub_git_proxy_port: 8001
cicdhub_git_proxy_ssl_port: 8101
cicdhub_git_non_ssl_port: 32080
cicdhub_git_ssl_port: 32443

cicdhub_nexus_proxy_target_host: nexus.cicdhub
cicdhub_nexus_proxy_port: 8002
cicdhub_nexus_proxy_ssl_port: 8102
# note we use a NodePort here because reverse proxy through K8s ingress does not work for Nexus
cicdhub_nexus_non_ssl_port: 32739
cicdhub_nexus_ssl_port: 32443

cicdhub_jenkins_master_proxy_target_host: jenkins-master.cicdhub
cicdhub_jenkins_master_proxy_port: 8003
cicdhub_jenkins_master_proxy_ssl_port: 8103
cicdhub_jenkins_master_non_ssl_port: 32080
cicdhub_jenkins_master_ssl_port: 32443
