- name: Copy helm values file
  template:
    src: "templates/cicdhub-values.yml"
    dest: "{{ cicdhub_installer_dir }}/cicdhub_values.yml"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"

- name: Copy custom helm values file
  template:
    src: "{{ cicdhub_values }}"
    dest: "{{ cicdhub_installer_dir }}/custom_cicdhub_values.yml"
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
  when: not (cicdhub_values is undefined or cicdhub_values is none or (cicdhub_values|trim == ''))

- name: Include custom helm values file
  set_fact:
    extra_values: "-f {{ cicdhub_installer_dir }}/custom_cicdhub_values.yml"
  when: not (cicdhub_values is undefined or cicdhub_values is none or (cicdhub_values|trim == ''))

- name: Install CICDHub
  command: helm install {{ helm_inst_cicdhub_chart }} --name cicdhub {% if docker_registry_values_path is defined %}-f {{ docker_registry_values_path }}{% endif %} -f {{ cicdhub_installer_dir }}/cicdhub_values.yml {% if extra_values is defined %}{{extra_values}}{% endif %}
