- name: Copy cicdhub volumes script
  copy: 
    remote_src: no
    src: "templates/volumes-init-create-cicdhub-directories.sh"
    dest: "{{ cicdhub_installer_dir }}/volumes-init-create-cicdhub-directories.sh"
  when: cicdhub_init_volumes_directories|bool == True
  
- name: Cleanup directory for Persistent Volumes
  file:
    path: /var/cicdhub/
    state: absent
  when: cicdhub_init_volumes_directories|bool == True

- name: Create directory for Persistent Volumes
  file:
    path: /var/cicdhub/
    state: directory
    mode: 0777
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
  when: cicdhub_init_volumes_directories|bool == True

- name: Run Volumes Init script
  shell: /bin/bash {{ cicdhub_installer_dir }}/volumes-init-create-cicdhub-directories.sh
  when: cicdhub_init_volumes_directories|bool == True
