---
####################################################################################
# General System Variables
####################################################################################

# Set the hostname of the target machine
hostname: "cicdhub"

####################################################################################
# Docker
####################################################################################

## Disable to prevent installation of Docker
docker: True

####################################################################################
# Kubernetes
####################################################################################

## Disable to prevent installation of Kubeadm
kubeadm: True

# In a multi network interface server you can specify which ip address to bind kubeadm to, otherwise comment this variable out
# and the default IP address discovered by Ansible will be used
# Set this to the IP you expect to use to access open ports on the target machine.
#kubeadm_advertise_address: 192.168.56.100

# With a vagrant environment the first network interface is used by Vagrant. The network interface to bind kubeadm to must be specified here, e.g. eth1.
# Change this variable to the main network interface or comment out and Ansible will use the default interface name.
# If you have set `kubeadm_advertise_address` then the recommended way determine the correct flannel_interface is to
# run `ifconfig` on the target machine, find the entry with the address you used on `kubeadm_advertise_address`, enter the name of that entry here.
#flannel_interface: "eth1"

# Set to 'yes' or 'True' to install the K8s Dashboard with Kubeadm
kube_dashboard: True

## Disable to prevent installation of Helm
helm: True

## List of Helm repositories to add
#helm_repos:
#  - name: repo-name
#    url: repo-addr

####################################################################################
# CICDHub
####################################################################################

## Disable to prevent installation of CICDHub components
cicdhub: True

##################################
# CICDHub - Helm Chart
##################################

cicdhub_chart_strategy: from_chart_src
cicdhub_chart_package: ../helm/cicdhub

## Path to a helm values file to be included on the install of Cicdhub Helm chart
cicdhub_values: cicdhub-helm-values.yml

## When using local volumes we need to create the directories and persistent volumes upfront
## When re-installing the CICDHub, disable only 'cicdhub_init_volumes_directories' to keep the existing directories and there contents.
cicdhub_init_volumes: True
cicdhub_init_volumes_directories: True

# Set CICDHub Openldap password
cicdhub_ldap_manager_password: admin

##################################
# CICDHub - Bootstrap Content
##################################

## Creates popular repository types in Nexus and the repository needed to bootstrap_aio and bootstrap_lm_packages
bootstrap_nexus_repositories: True

## Creates Git projects with the example NS and VNF services
## __PLAY substituted for the playbook directory
bootstrap_git_projects: True
bootstrap_git_project_defs:
  - name: hello-world-service
    content: "__PLAY/../bootstrap-content/example-service-projects/arm/hello-world-service"
    template: True
    template_fileexts: 
      - ".md"
  - name: docker-network
    content: "__PLAY/../bootstrap-content/example-service-projects/arm/docker-network"
    template: True
    template_fileexts: 
      - ".md"
  - name: ip-pbx
    content: "__PLAY/../bootstrap-content/example-service-projects/arm/ip-pbx"
    template: True
    template_fileexts: 
      - ".md"
  - name: sip-performance
    content: "__PLAY/../bootstrap-content/example-service-projects/arm/sip-performance"
    template: True
    template_fileexts: 
      - ".md"
  - name: getting-started
    content: "__PLAY/../bootstrap-content/cicdhub-docs"
    template: True
    template_fileexts: 
      - ".md"
bootstrap_git_username: cicdhub-admin
bootstrap_git_password: cicdhub-admin
bootstrap_git_email: admin@example.com

## Pushes an AIO config file to Nexus, that may be used on an AIO to pull the necessary packages from the this CICDHub
# LM packages only included if bootstrap_lm_packages is set to True
bootstrap_aio: True
bootstrap_aio_path: ../bootstrap-content/aio/aio-variables.yml

## Configures a Jenkins jnlp slave with lmctl installed
bootstrap_jenkins_lmctl_slave: True
bootstrap_jenkins_lmctl_version: 2.0.4
# Path to an Lmctl config file for the target LM environment to be used by the slave
bootstrap_jenkins_lmctl_config_file: ./jenkins-slave-lmctl-config.yaml

## Pushes the LM Helm Charts package to Nexus and Docker Images to the Docker Registry
## This makes them available for the All-in-one
bootstrap_lm_packages: False
bootstrap_lm_docker_source_path: ../bootstrap-content/lm-artifacts/lm-docker-source-<LM_VERSION>-dist.tgz
bootstrap_lm_helm_charts_path: ../bootstrap-content/lm-artifacts/lm-helm-charts-<LM_VERSION>-dist.tgz

####################################################################################
# Lifecycle Manager
####################################################################################

## Enable to install LM with the CICDHub
lm: False
## Enable to install a Apache2 based proxy for LM
lm_proxy: False

# When installing LM use the LM Helm Charts and Docker Images bootstraped earlier to the CICDHub
lm_use_bootstrap_sources: True

##################################
# Lifecycle Manager - Helm Charts
##################################

# Whilst "lm_use_bootstrap_sources" is True, LM will be installed with the bootstraped helm charts and images. 
# Use these only if you want to override the charts used.
#lm_charts_strategy: from_package
# Path to lm-helm-charts package (can be a file path or http address)
#lm_charts_package:

###################################
# Lifecycle Manager - Docker Images
###################################

# Whilst "lm_use_bootstrap_sources" is True, LM will be installed with the bootstraped helm charts and images. 
# Use these only if you want to override the docker images used.
#lm_docker_strategy: from_package
# Path to lm-docker-source package (can be file based or http)
#lm_docker_package:

##Switch to pulling Docker Images from a registry instead
#lm_docker_strategy: from_registry
#lm_docker_registry_host: registry_host
#lm_docker_registry_port: 5000

###################################
# Lifecycle Manager - Configuration
###################################

## Path to a helm values file to be included on the install of LM
lm_values: lm-helm-values.yml

## Run helper script to create directories for persistent volumes (required when using local volumes, which is the default)
lm_init_volumes: True

## Disable security by removing lm_secure
lm_secure: True
# Set to change the default Admin client secret 
#lm_admin_secret: admin

## Used to theme the LM UI
#lm_theme: False
#lm_theme_directory: path to directory containing theme.tar (mandatory name)
#lm_theme_name: name of theme

## The following are optionally installed with LM, set to False or comment out to disable them
lm_kibana_enabled: True
#lm_kafdrop_enabled: True

####################################################################################
# Ansible RM 
####################################################################################

## Enable to install the Ansible RM
arm: False

##################################
# Ansible RM - Helm Chart
##################################

## Locate Ansible RM chart on a path
arm_charts_strategy: path
## Path to the Ansible RM helm chart (can be file based or http)
arm_chart: https://github.com/IBM/osslm-ansible-resource-manager/releases/download/v1.3.4/osslm-ansible-resource-manager-1.3.4.tgz

##################################
# Ansible RM - Docker Images
##################################

## Pull the Docker Image from DockerHub (or a registry by including registry info on arm_docker_image e.g. host:port/osslm-ansible-rm)
arm_docker_strategy: from_image
arm_docker_image: accanto/osslm-ansible-rm
arm_docker_version: 1.3.4

## Disable https by removing arm_secure
arm_secure: True
