---
# cicdhub is the host that is used to install CICDHub in ICP and configure it
- hosts: cicdhub
  become: true
  gather_facts: no
  become_method: sudo
  vars_files:
    - ansible-variables-icp.yml
  tasks:
    - debug: 
        msg: "icp_host is required"
      failed_when: icp_host is not defined or icp_host == ""

    - debug: 
        msg: "icp_auth_token is required"
      failed_when: icp_auth_token is not defined or icp_auth_token == ""

    - import_role:
        name: initial-setup

    # note: this is needed to build custom Jenkins Docker image (and any others)
    - import_role:
        name: docker
      vars:
        docker_insecure_registries: 
        - "{{ icp_host }}:32736"
      when: docker|default(False)|bool == True

    - import_role:
        name: cicdhub
      when: cicdhub|default(False)|bool == True

# cicdhub-proxy is the host on which the CICDHub reverse proxy is installed
- hosts: cicdhub-proxy
  become: true
  gather_facts: no
  become_method: sudo
  vars_files:
    - ansible-variables-icp.yml
  tasks:
    - import_role:
        name: initial-setup

    - import_role:
        name: cicdhub-proxy
      when: cicdhub|default(False)|bool == True
