## Additional values to be provided when installing the LM helm charts

global:
  ldap: 
    managerPassword: "{{ cicdhub_ldap_manager_password }}"

cassandra:
  persistence:
    size: 500Mi

elasticsearch:
  master:
    persistence:
      size: 500Mi
  data:
    persistence:
      size: 50Gi

kafka:
  persistence:
    size: 1Gi
  kafkaHeapOptions: "-Xmx512M -Xms512M"
  livenessProbe:
    initialDelaySeconds: 90
    timeoutSeconds: 10
  readinessProbe:
    initialDelaySeconds: 90
    timeoutSeconds: 10
  zookeeper:
    env:
      ZK_HEAP_SIZE: "256M"
    persistence:
      size: 1Gi

##Using openldap provided by cicdhub helm chart instead
openldap:
  enabled: false
openldapInit:
  enabled: false

##Using Ingress installed by cicdhub
nginx-ingress:
  enabled: false

vault:
  resources:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 150m
    memory: 128Mi

### End helm-foundation

### lm-configurator ###
configurator:
  lmConfigImport:
    apollo:
      alm.apollo.janus.storage.cql.replication-factor: 1
      # number of JanusGraph ES index shards
      alm.apollo.janus.index.search.elasticsearch.create.ext.index.number_of_shards: 1
      # number of JanusGraph ES index replicas
      alm.apollo.janus.index.search.elasticsearch.create.ext.index.number_of_replicas: 0

    galileo:
      alm.galileo.janus.storage.cql.replication-factor: 1
      # number of JanusGraph ES index shards
      alm.galileo.janus.index.search.elasticsearch.create.ext.index.number_of_shards: 1
      # number of JanusGraph ES index replicas
      alm.galileo.janus.index.search.elasticsearch.create.ext.index.number_of_replicas: 0

    talledega:
      alm.talledega.janus.storage.cql.replication-factor: 1
      # number of JanusGraph ES index shards
      alm.talledega.janus.index.search.elasticsearch.create.ext.index.number_of_shards: 1
      # number of JanusGraph ES index replicas
      alm.talledega.janus.index.search.elasticsearch.create.ext.index.number_of_replicas: 0

      ## Specify any application config values with dot-separated key names
      # spring.data.cassandra.contact-points: cassandra-host  
      # spring.kafka.bootstrap-servers: kafka-host:9092
    ishtar:
      alm.ishtar.security.ldap.url: ldap://cicdhub-openldap:389

  # these settings are required for an Elasticsearch installation with a single data node to
  # ensure a green Elasticsearch cluster.
  janusgraph:
    config:
      alm:
        janusConfiguration:
          index:
            numberOfShards: 1
            # number of JanusGraph ES index replicas (default 1)
            numberOfReplicas: 0

### End lm-configurator ###

relay:
  service:
    type: NodePort

