- name: Check Apache Installed
  import_tasks: check_apache_installed.yml

- name: Ensure Python and Pip installed
  apt: 
    name: 
      - python
      - python-pip
    state: present 
    update_cache: yes
    
- name: Install pyopenssl
  shell: pip install pyopenssl

- name: Add CICDHub Proxy Site
  import_tasks: add_cicdhub.yml

- name: Set access addresses
  set_fact: 
    cicdhub_proxy_docker_registry_addr: "{% if cicdhub_proxy_ssl|default(False)|bool == True %}https{% else %}http{% endif %}://{{ kubeadm_advertise_address if kubeadm_advertise_address is defined else hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{cicdhub_docker_registry_proxy_port}}"
    cicdhub_proxy_git_addr: "{% if cicdhub_proxy_ssl|default(False)|bool == True %}https{% else %}http{% endif %}://{{ kubeadm_advertise_address if kubeadm_advertise_address is defined else hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{cicdhub_git_proxy_port}}"
    cicdhub_proxy_nexus_addr: "{% if cicdhub_proxy_ssl|default(False)|bool == True %}https{% else %}http{% endif %}://{{ kubeadm_advertise_address if kubeadm_advertise_address is defined else hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{cicdhub_nexus_proxy_port}}"
    cicdhub_proxy_jenkins_master_addr: "{% if cicdhub_proxy_ssl|default(False)|bool == True %}https{% else %}http{% endif %}://{{ kubeadm_advertise_address if kubeadm_advertise_address is defined else hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:{{cicdhub_jenkins_master_proxy_port}}"
