- name: Wait for Nexus to be ready
  uri:
    url: "{{ cicdhub_addr_nexus }}"
    method: HEAD
    status_code: 200, 503, 308
    return_content: yes
  register: nexus_result
  until: nexus_result['status']|default(0) == 200
  retries: 100
  delay: 10


- name: Get PyPi
  uri:
    url: "{{ cicdhub_addr_nexus }}/repository/pypi/"
    method: GET
    force_basic_auth: yes
    user: admin
    password: admin123
    status_code: 200, 404
    headers:
      accept: "application/json"
  register: pypi_result

- name: Get PyPi script
  uri:
    url: "{{ cicdhub_addr_nexus }}/service/rest/v1/script/pypi"
    method: GET
    force_basic_auth: yes
    user: admin
    password: admin123
    status_code: -1, 200, 404
    headers:
      accept: "application/json"
  when: pypi_result != 200
  register: pypi_script_result

- name: Create PyPi script
  uri:
    url: "{{ cicdhub_addr_nexus }}/service/rest/v1/script"
    method: POST
    force_basic_auth: yes
    user: admin
    password: admin123
    headers:
      accept: "application/json"
      Content-Type: "application/json"
    body: "{ \"name\": \"pypi\", \"content\": \"import org.sonatype.nexus.blobstore.api.BlobStoreManager; import org.sonatype.nexus.repository.storage.WritePolicy; import org.sonatype.nexus.repository.maven.VersionPolicy; import org.sonatype.nexus.repository.maven.LayoutPolicy; repository.createPyPiHosted('pypi', 'default', false, WritePolicy.ALLOW_ONCE);\", \"type\": \"groovy\"}"
    status_code: 204
  when: pypi_script_result.status != 200

- name: Run PyPi script
  uri:
    url: "{{ cicdhub_addr_nexus }}/service/rest/v1/script/pypi/run"
    method: POST
    force_basic_auth: yes
    user: admin
    password: admin123
    headers:
      accept: "application/json"
      Content-Type: "text/plain"
    body: "string"
    status_code: 200
  when: pypi_result.status != 200

- name: Get PyPi All
  uri:
    url: "{{ cicdhub_addr_nexus }}/repository/pypi-all/"
    method: GET
    force_basic_auth: yes
    user: admin
    password: admin123
    status_code: 200, 404
    headers:
      accept: "application/json"
  register: pypiall_result

- name: Get Pypiall script
  uri:
    url: "{{ cicdhub_addr_nexus }}/service/rest/v1/script/pypiall"
    method: GET
    force_basic_auth: yes
    user: admin
    password: admin123
    status_code: -1, 200, 404
    headers:
      accept: "application/json"
  register: pypiall_script_result

- name: Create Pypiall script
  uri:
    url: "{{ cicdhub_addr_nexus }}/service/rest/v1/script"
    method: POST
    force_basic_auth: yes
    user: admin
    password: admin123
    headers:
      accept: "application/json"
      Content-Type: "application/json"
    body: "{ \"name\": \"pypiall\", \"content\": \"import org.sonatype.nexus.blobstore.api.BlobStoreManager; import org.sonatype.nexus.repository.storage.WritePolicy; import org.sonatype.nexus.repository.maven.VersionPolicy; import org.sonatype.nexus.repository.maven.LayoutPolicy; repository.createPyPiGroup('pypi-all', ['pypi'], 'default');\", \"type\": \"groovy\"}"
    status_code: 204
  when: pypiall_script_result.status != 200

- name: Run PyPiall script
  uri:
    url: "{{ cicdhub_addr_nexus }}/service/rest/v1/script/pypiall/run"
    method: POST
    force_basic_auth: yes
    user: admin
    password: admin123
    headers:
      accept: "application/json"
      Content-Type: "text/plain"
    body: "string"
    status_code: 200
  when: pypiall_result.status != 200

- name: Get PyPi Proxy
  uri:
    url: "{{ cicdhub_addr_nexus }}/repository/pypi-proxy/"
    method: GET
    force_basic_auth: yes
    user: admin
    password: admin123
    status_code: 200, 404
    headers:
      accept: "application/json"
  register: pypiproxy_result

- name: Get Pypiproxy script
  uri:
    url: "{{ cicdhub_addr_nexus }}/service/rest/v1/script/pypiproxy"
    method: GET
    force_basic_auth: yes
    user: admin
    password: admin123
    status_code: -1, 200, 404
    headers:
      accept: "application/json"
  register: pypiproxy_script_result

- name: Create Pypiproxy script
  uri:
    url: "{{ cicdhub_addr_nexus }}/service/rest/v1/script"
    method: POST
    force_basic_auth: yes
    user: admin
    password: admin123
    headers:
      accept: "application/json"
      Content-Type: "application/json"
    body: "{ \"name\": \"pypiproxy\", \"content\": \"import org.sonatype.nexus.blobstore.api.BlobStoreManager; import org.sonatype.nexus.repository.storage.WritePolicy; import org.sonatype.nexus.repository.maven.VersionPolicy; import org.sonatype.nexus.repository.maven.LayoutPolicy; repository.createPyPiProxy('pypi-proxy', 'https://pypi.org/', 'default', false);\", \"type\": \"groovy\"}"
    status_code: 204
  when: pypiproxy_script_result.status != 200

- name: Run Pypiproxy script
  uri:
    url: "{{ cicdhub_addr_nexus }}/service/rest/v1/script/pypiproxy/run"
    method: POST
    force_basic_auth: yes
    user: admin
    password: admin123
    headers:
      accept: "application/json"
      Content-Type: "text/plain"
    body: "string"
    status_code: 200
  when: pypiproxy_result.status != 200

- name: Get raw script
  uri:
    url: "{{ cicdhub_addr_nexus }}/service/rest/v1/script/raw"
    method: GET
    force_basic_auth: yes
    user: admin
    password: admin123
    status_code: -1, 200, 404
    headers:
      accept: "application/json"
  register: raw_script_result

- name: Create raw repo script
  uri:
    url: "{{ cicdhub_addr_nexus }}/service/rest/v1/script"
    method: POST
    force_basic_auth: yes
    user: admin
    password: admin123
    headers:
      accept: "application/json"
      Content-Type: "application/json"
    body: "{ \"name\": \"raw\", \"content\": \"import org.sonatype.nexus.blobstore.api.BlobStoreManager; import org.sonatype.nexus.repository.storage.WritePolicy; import org.sonatype.nexus.repository.maven.VersionPolicy; import org.sonatype.nexus.repository.maven.LayoutPolicy; repository.createRawHosted('raw', 'default', false, WritePolicy.ALLOW_ONCE);\", \"type\": \"groovy\"}"
    status_code: 204
  when: raw_script_result.status != 200

- name: Run raw script
  uri:
    url: "{{ cicdhub_addr_nexus }}/service/rest/v1/script/raw/run"
    method: POST
    force_basic_auth: yes
    user: admin
    password: admin123
    headers:
      accept: "application/json"
      Content-Type: "text/plain"
    body: "string"
    status_code: 200
  # when: raw_result.status != 200




- name: Get Rubygems
  uri:
    url: "{{ cicdhub_addr_nexus }}/repository/rubygems/"
    method: GET
    force_basic_auth: yes
    user: admin
    password: admin123
    status_code: 200, 404
    headers:
      accept: "application/json"
  register: rubygems_result

- name: Get Ruby Gems script
  uri:
    url: "{{ cicdhub_addr_nexus }}/service/rest/v1/script/rubygems"
    method: GET
    force_basic_auth: yes
    user: admin
    password: admin123
    status_code: -1, 200, 404
    headers:
      accept: "application/json"
  register: rubygems_script_result

- name: Create Ruby Gems script
  uri:
    url: "{{ cicdhub_addr_nexus }}/service/rest/v1/script"
    method: POST
    force_basic_auth: yes
    user: admin
    password: admin123
    headers:
      accept: "application/json"
      Content-Type: "application/json"
    body: "{ \"name\": \"rubygems\", \"content\": \"import org.sonatype.nexus.blobstore.api.BlobStoreManager; import org.sonatype.nexus.repository.storage.WritePolicy; import org.sonatype.nexus.repository.maven.VersionPolicy; import org.sonatype.nexus.repository.maven.LayoutPolicy; repository.createRubygemsHosted('rubygems', 'default', false, WritePolicy.ALLOW_ONCE);\", \"type\": \"groovy\"}"
    status_code: 204
  when: rubygems_script_result.status != 200

- name: Run Ruby Gems script
  uri:
    url: "{{ cicdhub_addr_nexus }}/service/rest/v1/script/rubygems/run"
    method: POST
    force_basic_auth: yes
    user: admin
    password: admin123
    headers:
      accept: "application/json"
      Content-Type: "text/plain"
    body: "string"
    status_code: 200
  when: rubygems_result.status != 200
