dependencies:
  - name: sonatype-nexus
    alias: nexus
    version: 1.18.4
    repository: "@stable"
    condition: nexus.enabled

  - name: jenkins
    version: 1.3.5
    repository: "@stable"
    condition: jenkins.enabled

  - name: gogs
    version: 0.7.10
    repository: "@incubator"
    condition: gogs.enabled

  - name: docker-registry
    alias: dockerregistry
    version: 1.8.0
    repository: "@stable"
    condition: dockerregistry.enabled
    
  - name: nginx-ingress
    version: 1.10.0
    repository: "@stable"
    condition: nginx-ingress.enabled

  - name: openldap
    version: 1.1.0
    repository: "@stable"
    condition: openldap.enabled